name: Build
on:
  workflow_call:
  push:
    branches:
      - main

jobs:
  build:
    name: Build the project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Download the latest release
        run: wget https://github.com/llvm-mos/llvm-mos-sdk/releases/latest/download/llvm-mos-linux.tar.xz
      
      - name: Extract the archive
        run: tar -xJf llvm-mos-linux.tar.xz
      
      - name: Add the LLVM-MOS directory to the PATH
        run: export PATH=$PATH:$GITHUB_WORKSPACE/llvm-mos/bin # Does this even work?
      
      - name: Build the projct
        run: make compile
      
      - name: Upload the binaries to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: bios
          path: $GITHUB_WORKSPACE/build/bios.bin
